version: '3.8'

services:
  telegram_rag_bot:
    build: .
    container_name: telegram_rag_bot
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
    volumes:
      - ./rag_services.csv:/app/rag_services.csv
    restart: unless-stopped